"""Add chart_cache table

Revision ID: 028ea246f409
Revises: 900f1ca60dc4
Create Date: 2026-05-11 20:08:22.894780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028ea246f409'
down_revision = '900f1ca60dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('prices_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_id', 'days', name='uq_chart_cache_coin_days')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_cache')
    # ### end Alembic commands ###
