"""drop price_history table

Revision ID: 7057b0d91ab3
Revises: 028ea246f409
Create Date: 2026-05-11 21:02:49.245852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7057b0d91ab3'
down_revision = '028ea246f409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_coin_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_timestamp'))

    op.drop_table('price_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coin_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], name=op.f('price_history_coin_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('price_history_pkey'))
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_coin_id'), ['coin_id'], unique=False)

    # ### end Alembic commands ###
