"""initial schema: users, coins, news, watchlist, price_history

Revision ID: 8708394d0c3a
Revises: 
Create Date: 2026-05-08 13:29:43.597515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8708394d0c3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_change_percentage_24h', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('circulating_supply', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('total_supply', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('ath', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ath_change_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ath_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('atl_change_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('atl_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coins_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_symbol'), ['symbol'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_coin_id'), ['coin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_timestamp'), ['timestamp'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'coin_id', name='uix_user_coin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_price_history_coin_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('news')
    with op.batch_alter_table('coins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coins_symbol'))
        batch_op.drop_index(batch_op.f('ix_coins_name'))

    op.drop_table('coins')
    # ### end Alembic commands ###
