"""increase coin_id length in price_history and watchlist

Revision ID: 900f1ca60dc4
Revises: 9363ee8d15ac
Create Date: 2026-05-10 09:14:36.584783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900f1ca60dc4'
down_revision = '9363ee8d15ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('coin_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('coin_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('coin_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('coin_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
